#!/bin/bash

sudo dnf -y update
sudo dnf -y install \
    java-1.8.0-openjdk \
    java-11-openjdk \
    dnf-plugins-core \
    fuse-overlayfs \
    android-tools \
    neofetch \
    xmodmap \
    xdotool \
    cmatrix \
    dconf \
    snapd \
    unzip \
    htop \
    wget \
    zip \
    gh

sudo dnf -y install http://rpms.remirepo.net/fedora/remi-release-36.rpm
sudo dnf -y module install php:remi-8.1
sudo dnf -y install \
    php \
    php-gd \
    php-fpm \
    php-zip \
    php-intl \
    php-devel \
    php-mcrypt \
    php-mysqlnd \
    php-mbstring \
    php-memcache \
    php-imagick \
    php-xdebug \
    php-xmlrpc \
    php-swoole \
    php-curl \
    php-pear \
    php-json

# RETOQUES
sudo dnf install gnome-tweaks gnome-extensions-app

# GOOGLE CHROME
sudo rpm --import https://dl.google.com/linux/linux_signing_key.pub
sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
sudo dnf -y install google-chrome-stable_current_x86_64.rpm

# DOCKER
sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
sudo dnf -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
sudo systemctl start docker

# REMOVE LIBREOFFICE
sudo dnf -y remove $(dnf list installed | grep libreoffice | grep -o -E "^\S+")