#!/bin/bash

sudo apt update
sudo apt install -y \
    x11-xserver-utils \
    default-jdk \
    x11-utils \
    dconf-cli \
    neofetch \
    xdotool \
    cmatrix \
    expect \
    snapd \
    unzip \
    htop \
    wget \
    curl \
    adb \
    zip \
    gh

sudo apt-get install -y uidmap

sudo apt install -y \
    software-properties-common \
    libcurl4-openssl-dev \
    apt-transport-https \
    ca-certificates \
    gnome-tweaks \
    lsb-release \
    gnupg

LC_ALL=C.UTF-8

sudo add-apt-repository universe
sudo add-apt-repository ppa:ondrej/php

# PHP
sudo apt install -y php8.1
sudo apt -y install php8.1-gd php8.1-dev php8.1-fpm php8.1-zip php8.1-intl php8.1-mysql php8.1-mcrypt php8.1-mbstring php8.1-memcache php8.1-imagick php8.1-xdebug php8.1-xmlrpc php8.1-curl

sudo pecl install --alldeps --configureoptions 'enable-sockets="yes" enable-openssl="yes" enable-http2="yes" enable-mysqlnd="yes" enable-swoole-json="yes" enable-swoole-curl="yes" enable-cares="yes" with-postgres="no"' openswoole

# GOOGLE CHROME
sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb

# DOCKER
mkdir -p /etc/apt/keyrings

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
gpg --dearmor -o /etc/apt/keyrings/docker.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
      https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get install -y \
    docker-compose-plugin \
    docker-ce-cli \
    containerd.io \
    docker-ce

# REMOVE LIBREOFFICE
sudo apt -y remove $(apt list --installed | grep libreoffice | grep -o -E "^[^\/]+")