#!/bin/bash
GITHUB_REPO="https://raw.githubusercontent.com/byancode/linux"
DISTRO=$(cat /etc/os-release | grep "^ID=" | cut -d= -f2)

bash <(curl $GITHUB_REPO/master/distros/$DISTRO)

# CREATE FOLDERS
mkdir ~/files
mkdir ~/programs
mkdir ~/workspace

git config --global user.name   "Byancode"
git config --global user.email  "byancode@gmail.com"

sudo systemctl enable --now snapd.socket
sudo ln -s /var/lib/snapd/snap /snap

# COMPOSER
sudo wget https://getcomposer.org/composer-stable.phar -O /usr/local/bin/composer
sudo chmod +x /usr/local/bin/composer

# ROOTLESS DOCKER
sudo systemctl disable --now docker.service docker.socket
curl -fsSL https://get.docker.com/rootless | sh

# HTTPTOOLKIT
HTTPTOOLKIT_VERSION=1.8.1
mkdir ~/programs/HttpToolKit
sudo wget https://github.com/httptoolkit/httptoolkit-desktop/releases/download/v${HTTPTOOLKIT_VERSION}/HttpToolkit-linux-x64-${HTTPTOOLKIT_VERSION}.zip
unzip HttpToolkit-linux-x64-${HTTPTOOLKIT_VERSION}.zip -d ~/programs/HttpToolKit

# NVM
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

source ~/.bashrc

nvm install 18.2.0
npm install -g yarn

sudo snap install flutter --classic --channel=stable
sudo snap install android-studio --classic --stable
sudo snap install kotlin --classic
sudo snap install gradle --classic
sudo snap install telegram-desktop
sudo snap install code --classic
sudo snap install runjs --edge
sudo snap install obs-studio
sudo snap install snap-store
sudo snap install insomnia
sudo snap install postman
sudo snap install slack

# ADD VSCODE ON CONTEXTMENU NAUTIUS
bash -c "$(wget -qO- https://raw.githubusercontent.com/harry-cpp/code-nautilus/master/install.sh)"

# download wallpaper
curl -fsSL "$GITHUB_REPO/main/wallpapers/ultrawide.jpg" > ~/files/ultrawide.jpg
curl -fsSL "$GITHUB_REPO/main/wallpapers/laptop.jpg" > ~/files/laptop.jpg


# download and install JetBrain Mono font from Google Fonts
sudo curl -fsSL https://fonts.google.com/download?family=JetBrains%20Mono -o ~/files/JetBrainsMono.zip
sudo mkdir -p ~/files/JetBrainsMono
sudo unzip ~/files/JetBrainsMono.zip -d ~/files/JetBrainsMono
sudo mkdir -p ~/.local/share/fonts/jetbrains-mono
sudo cp -r ~/files/JetBrainsMono/static/* ~/.local/share/fonts/jetbrains-mono


echo '
keycode 232=F1 F1 XF86MonBrightnessDown
keycode 233=F2 F2 XF86MonBrightnessUp
keycode 128=F3 F3 XF86LaunchA
keycode 212=F4 F4 XF86LaunchB
keycode 237=F5 F5 XF86KbdBrightnessDown
keycode 238=F6 F6 XF86KbdBrightnessUp
keycode 173=F7 F7 XF86AudioPrev
keycode 172=F8 F8 XF86AudioPlay
keycode 171=F9 F9 XF86AudioNext
keycode 121=F10 F10 XF86AudioMute
keycode 122=F11 F11 XF86AudioLowerVolume
keycode 123=F12 F12 XF86AudioRaiseVolume

keycode  57=n N ntilde Ntilde

keycode 108=Mode_switch Mode_switch
' > ~/.xmodmap

# execute xmodmap
# xmodmap ~/.xmodmap

# show configuration keycodes
# xmodmap -pke

# reset xmodmap
# setxkbmap -option

echo '#!/bin/bash
git add . && git commit -m "$(echo $@)"
' >> ~/bin/gac && chmod +x ~/bin/gac

echo '#!/bin/bash
git add . && git commit -m "$(echo $@)" && git push
' >> ~/bin/ggp && chmod +x ~/bin/ggp

echo '#!/bin/bash
git init
git add .
git commit -m "first commit"
git branch -M main
git remote add origin git@github.com:$(echo $1).git
git push -u origin main
' >> ~/bin/gii && chmod +x ~/bin/gii


echo '#!/bin/bash
rm -rf .git
git init
gh repo create $(echo $1) --private --source=. --remote=upstream
git add .
git commit -m "first commit"
git push --set-upstream upstream master
' >> ~/bin/ghc && chmod +x ~/bin/ghc


echo '
# Add this to .bashrc or .zshrc or its equivalent
transfer(){ if [ $# -eq 0 ];then echo "No arguments specified.\nUsage:\n transfer <file|directory>\n ... | transfer <file_name>">&2;return 1;fi;if tty -s;then file="$1";file_name=$(basename "$file");if [ ! -e "$file" ];then echo "$file: No such file or directory">&2;return 1;fi;if [ -d "$file" ];then file_name="$file_name.zip" ,;(cd "$file"&&zip -r -q - .)|curl --progress-bar --upload-file "-" "https://transfer.sh/$file_name"|tee /dev/null,;else cat "$file"|curl --progress-bar --upload-file "-" "https://transfer.sh/$file_name"|tee /dev/null;fi;else file_name=$1;curl --progress-bar --upload-file "-" "https://transfer.sh/$file_name"|tee /dev/null;fi;}
' >> ~/.bashrc